version: '3.8'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    volumes:
      - "./dynamodb-data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  python-app:
    build: .
    container_name: python-app
    ports:
      - "5000:5000"
  