version: '3.8'

services:
  scraper:
    build: .
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - TZ=America/New_York
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0 if open('/app/logs/scraper.log', 'a').close() is None else 1)"]
      interval: 1m
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
